### ISSUE TITLE
Unable to install Virtual Environment (Windows 10)

### ISSUE THREAD

**Issue by pma2** [LDSSA/heroku-model-deploy#6]
Trying to follow:
https://medium.com/hugo-ferreiras-blog/using-windows-subsystem-for-linux-for-data-science-9a8e68d7610c
I can install the subsystem for Linux and enable it:
![image](https://user-images.githubusercontent.com/38791092/44591830-ab063f80-a7b6-11e8-9d5c-9bd2f39702b2.png)
But I cannot install Ubuntu:
![image](https://user-images.githubusercontent.com/38791092/44591860-beb1a600-a7b6-11e8-8c84-d260ba497027.png)
Says I need to update Windows 10 version.
To update Windows 10 I need to uninstall my anti-virus:
![image](https://user-images.githubusercontent.com/38791092/44591933-ebfe5400-a7b6-11e8-8792-3cc155ac592f.png)
That I cannot do... corporate PC...
What should I do? 
Thanks

**Comment by hershaw** [comment]
He ended up just getting an old desktop and installing ubuntu on it.
