### ISSUE TITLE
AttributeError: 'module' object has no attribute 'run'

### ISSUE THREAD

**Issue by migvieira** [LDSSA/heroku-model-deploy#8]
when activating the project's virtual environment
$ pipenv shell
I get an AttributeError: 'module' object has no attribute 'run'

I've found someone saying on stackoverflow that the subprocess.run() function only exists in Python 3.5 and newer. (and I have python 3.4.4)
Did someone had to upgrade python's version?

**Comment by hershaw** [comment]
Can you please show how you created the virtualenv?

Also, as mentioned in slack, can you try it with python3.6? pipenv is a young project and still has some issues so it would be good to stick to the script as closely as possible :)

**Comment by migvieira** [comment]
I followed Hugo's post, and created a Windows Subsystem for Linux
then I installed pipenv
pipenv install -r requirements.txt
then when I went to actvate the environment I got this error

I'll try to use python 3.6 ( I have 3.4.4)
